set(TARGET llama-layersplit)
add_executable(${TARGET} layersplit.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_link_libraries(${TARGET} PRIVATE llama-common llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)

set(TARGET llama-hetero-ubatch)
add_executable(${TARGET} hetero-ubatch.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_link_libraries(${TARGET} PRIVATE llama-common llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)

set(TARGET llama-stage-direct-relay)
add_executable(${TARGET} stage-direct-relay.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_include_directories(${TARGET} PRIVATE ../gguf-hash/deps)
target_link_libraries(${TARGET} PRIVATE sha256)
target_compile_features(${TARGET} PRIVATE cxx_std_17)

set(TARGET llama-token-codec)
add_executable(${TARGET} token-codec.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_link_libraries(${TARGET} PRIVATE llama-common llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)
