"""Unified heterogeneous inference scheduler."""

from ._internal.compat import adapt_legacy_profile, adapt_legacy_request, adapt_legacy_route
from ._internal.capacity import (
    LAYER_PLACEMENT_SCHEMA,
    CapacityError,
    CapacityPlanner,
    DeviceMemoryCapacity,
    LayerPlacementCandidate,
    LayerPlacementContract,
)
from ._internal.dynamic_residency import (
    DYNAMIC_FALLBACK_CONTRACT_SCHEMA,
    DYNAMIC_FALLBACK_RECEIPT_SCHEMA,
    DYNAMIC_RESIDENCY_ACTIONS,
    DYNAMIC_RESIDENCY_RECEIPT_SCHEMA,
    DYNAMIC_RESIDENCY_RECEIPT_STATUSES,
    DYNAMIC_RESIDENCY_SCHEMA,
    DYNAMIC_RESIDENCY_TRANSITION_MODES,
    DynamicFallbackServiceContract,
    DynamicFallbackServiceReceipt,
    DynamicResidencyCandidate,
    DynamicResidencyDecision,
    DynamicResidencyError,
    DynamicResidencyReceipt,
    DynamicResidencySnapshot,
    DynamicWeightPlacement,
    DynamicWeightPlacementSpec,
    ResidencyTransitionAction,
    apply_dynamic_residency_receipt,
    select_dynamic_residency_transition,
)
from ._internal.gpu_backfill import (
    GPU_BACKFILL_SCHEMA,
    GPU_WAVEFRONT_OBJECTIVES,
    GPU_WAVEFRONT_SCHEMA,
    GpuBackfillCandidate,
    GpuBackfillDecision,
    GpuBackfillError,
    GpuBubbleWindow,
    GpuReadyChunk,
    GpuWavefrontDecision,
    GpuWavefrontSnapshot,
    select_gpu_backfill,
    select_gpu_wavefront_backfill,
)
from ._internal.cohort import (
    COHORT_POLICY_MODES,
    CohortDecision,
    CohortPolicy,
    CohortScheduleError,
    CohortPlanner,
    cohort_decision_to_json,
)
from ._internal.certified_cohort import (
    CertifiedCohortError,
    CertifiedCohortProfile,
    load_certified_cohort,
)
from .scheduler import (
    DynamicPlacementLease,
    DynamicResidencySchedule,
    GpuBackfillSchedule,
    GpuWavefrontSchedule,
    LifecycleProfileSet,
    LifecycleReceipt,
    PhoneArbiterSchedule,
    PhoneOffloadSchedule,
    UnifiedScheduleError,
    UnifiedScheduler,
)
from ._internal.executor import (
    EXECUTION_PLAN_SCHEMA,
    ExecutionPlan,
    ExecutionPlanError,
    build_execution_plan,
    load_execution_plan,
    write_execution_plan,
)
from ._internal.policy import (
    ENERGY_STATUSES,
    GRANULARITIES,
    OVERLAP_STATUSES,
    POLICY_MODES,
    PROFILE_SCHEMA,
    QUALITY_RANK,
    AffineCost,
    Candidate,
    Decision,
    EnergyDomain,
    EnergyProfile,
    RoutePolicy,
    KernelEnergyEstimate,
    KernelEnergyProfile,
    LatencyProfile,
    LatencyVariant,
    LeaseDemand,
    LeasePlan,
    LeasePreview,
    LeaseRecord,
    MarginalSystemCostContext,
    OperatorEnergyCost,
    OperatorWork,
    OverlapProfile,
    PolicyConfig,
    ProfileBundle,
    Request,
    ResourceLeaseProfile,
    ResourceProfile,
    ResourceTimeline,
    RouteProfile,
    SchedulerError,
    decision_to_json,
    estimate_kernel_energy,
)
from ._internal.placement import (
    LOAD_STATUSES,
    PLACEMENT_PROFILE_SCHEMA,
    PLACEMENT_STATUSES,
    ComputeStep,
    ExecutionBranch,
    ExecutionStep,
    HierarchicalPlacementPlanner,
    LayerDecision,
    MemoryPoolProfile,
    OperatorCandidate,
    OperatorDecision,
    OperatorNode,
    PlacementDevice,
    PlacementError,
    PlacementHardwareProfile,
    PlacementPlan,
    ProfiledEnergyDomain,
    ProfiledKernel,
    ResidentAllocation,
    TaskPlacementDecision,
    TaskRoute,
    TransferDecision,
    TransferLink,
    TransferStep,
    placement_plan_to_json,
    task_placement_to_json,
)
from ._internal.offload import (
    OFFLOAD_CONTRACT_SCHEMA,
    BackendArtifact,
    OffloadError,
    OperatorOffloadContract,
    OperatorOffloadInvocation,
    PhoneBackendConfig,
)
from ._internal.operator_split import (
    OPERATOR_SPLIT_SCHEMA,
    BalancedSplitEstimate,
    OperatorSplitError,
    OperatorSplitInvocation,
    OperatorSplitPolicy,
    OperatorWorkSummary,
    ParallelSplitBalance,
    ParallelSplitShapeMeasurement,
    ShapeBucket,
    balance_parallel_split,
    parse_split_table,
    select_split_columns,
    split_table_text,
)
from ._internal.phone_transport import (
    PHONE_TRANSPORT_SCHEMA,
    DmaBufTransfer,
    PhoneTransportContract,
    PhoneTransportError,
)
from ._internal.phone_arbiter import (
    PHONE_ARBITER_PRIORITIES,
    PHONE_ARBITER_SCHEMA,
    PhoneArbiterDecision,
    PhoneArbiterError,
    PhoneArbiterQueue,
    PhoneArbiterWindow,
    PhoneReadyWork,
    select_phone_arbiter_work,
)
from ._internal.phone_residency import (
    PHONE_OFFLOAD_EXECUTION_MODES,
    PHONE_RESIDENCY_SCHEMA,
    SESSION_STATES,
    PhoneArmGroup,
    PhoneArmSignal,
    PhoneOffloadCandidate,
    PhoneOffloadDecision,
    PhoneResidencyError,
    PhoneResidencyPlan,
    PhoneResidencySnapshot,
    PhoneSessionPlan,
    PhoneSessionReceipt,
    ResidentPhoneSlice,
    build_arm_group,
    build_arm_signal,
    select_energy_positive_offload,
    validate_session_transition,
)
from ._internal.profile_catalog import (
    ProfileCatalogError,
    canonical_profile_bytes,
    load_lifecycle_profile_set,
    load_profile_bundle,
)
from ._internal.profile_materializer import (
    GIB,
    KERNEL_CAMPAIGN_SCHEMA,
    materialize_matmul_profile,
)
from ._internal.residency import (
    RESIDENCY_PROBLEM_SCHEMA,
    CohortRoute,
    ParallelAssignment,
    QueueRequest,
    ResidencyPhase,
    ResidencyResource,
    ResidencySchedulerError,
    ResidencySequence,
    ResidencySwitch,
    RouteSchedule,
    ScheduledRequest,
    optimize_parallel_assignment,
    parallel_assignment_to_json,
    plan_residency_sequence,
    residency_sequence_to_json,
    schedule_route,
    scheduled_request_to_json,
    solve_residency_problem,
)
from ._internal.runtime_gates import (
    RequestSemantics,
    ResourceRequirement as RuntimeResourceRequirement,
    RouteRuntimeContract,
    RuntimeGateError,
    RuntimeGateReceipt,
    RuntimeResourceState,
    RuntimeSnapshot,
    SemanticCapabilities,
    evaluate_runtime_gate,
)
from ._internal.runtime_placement import (
    RUNTIME_PLACEMENT_SCHEMA,
    RuntimePlacementCandidate,
    RuntimePlacementDecision,
    RuntimePlacementError,
    RuntimePlacementPlanner,
    RuntimePlacementSnapshot,
)
from ._internal.runtime_cost import (
    RUNTIME_COST_SCHEMA,
    RuntimeCostError,
    RuntimeCostEstimateSet,
    RuntimeCostEstimator,
    RuntimeExecutorBinding,
    RuntimeExecutorRegistry,
    RuntimeMemoryDemand,
    RuntimeModelArtifact,
    RuntimeRouteCostEstimate,
)
from ._internal.online_placement import (
    ONLINE_PLACEMENT_SCHEMA,
    ONLINE_ROUTE_FAMILIES,
    OnlinePlacementError,
    OnlinePlacementReceipt,
    OnlinePlacementTracker,
    OnlineRouteFamilyEstimate,
)
from ._internal.runtime_queue import (
    RUNTIME_DISPATCH_QUEUE_SCHEMA,
    BackgroundRuntimeMonitor,
    BackgroundRuntimeSnapshot,
    RuntimeDispatchQueue,
    RuntimeDispatchReceipt,
    RuntimeQueueError,
)
from ._internal.types import (
    AccountingContract,
    AccountingKind,
    AccountingScope,
    ApplicabilityContract,
    CandidateSet,
    EnergyComponent,
    FeatureRange,
    MemoryRequirement,
    MetricEstimate,
    ModelIdentity,
    OverlapEstimate,
    PhaseLease,
    PlacementGranularity,
    QualityClass,
    QualityContract,
    ResidencyRequirement,
    ResourceRequirement,
    RouteAlternative,
    RouteMaturity,
    SchedulingUnit,
    SchedulerContractError,
    UnitKind,
    canonical_json,
    canonical_sha256,
    make_work_set_hash,
)
from .trace import (
    AdaptedTrace,
    BURSTGPT_TRACE_SCHEMAS,
    MIXED_TRACE_SCHEMA,
    MIXED_TRACE_SCHEMAS,
    SEMANTIC_SOURCE_TRACE_SCHEMA,
    SMALL_MODEL_OVERLAY_TRACE_SCHEMA,
    SOURCE_TRACE_SCHEMA,
    TraceError,
    load_burstgpt_trace,
    load_mixed_model_trace,
    load_trace,
    sha256_file,
)


_MATMUL_EXPORTS = {
    "MATMUL_DEVICE_ORDER": "DEVICE_ORDER",
    "MATMUL_PROFILE_SCHEMA": "PROFILE_SCHEMA",
    "MATMUL_PROFILE_STATUSES": "PROFILE_STATUSES",
    "MATMUL_QUEUE_TRANSITIONS": "QUEUE_TRANSITIONS",
    "MATMUL_RESULT_SCHEMA": "RESULT_SCHEMA",
    "MATMUL_WORKLOAD_SCHEMA": "WORKLOAD_SCHEMA",
    "ActivationState": "ActivationState",
    "CandidatePlan": "CandidatePlan",
    "EnergyDomainProfile": "EnergyDomainProfile",
    "FollowOp": "FollowOp",
    "KernelCatalog": "KernelCatalog",
    "KernelEstimate": "KernelEstimate",
    "LinkCatalog": "LinkCatalog",
    "MatmulDeviceProfile": "MatmulDeviceProfile",
    "MatmulKernelProfile": "MatmulKernelProfile",
    "MatmulLinkProfile": "MatmulLinkProfile",
    "MatmulOp": "MatmulOp",
    "MatmulPolicy": "MatmulPolicy",
    "MatmulScheduleError": "MatmulScheduleError",
    "MatmulSystemProfile": "MatmulSystemProfile",
    "MatmulPlanner": "MatmulPlanner",
    "MemoryLedger": "MemoryLedger",
    "MemoryPreview": "MemoryPreview",
    "ModelProgram": "ModelProgram",
    "Phase": "Phase",
    "PowerInterval": "PowerInterval",
    "PowerTimeline": "PowerTimeline",
    "ProgramOp": "ProgramOp",
    "TransferEstimate": "TransferEstimate",
    "load_matmul_profile": "load_profile",
    "load_matmul_workload": "load_workload",
    "run_matmul_workload": "run_workload",
}


def __getattr__(name: str) -> object:
    try:
        target = _MATMUL_EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(name) from exc
    from importlib import import_module

    module = import_module("._internal.matmul", __name__)
    value = getattr(module, target)
    globals()[name] = value
    return value

__all__ = [
    "ENERGY_STATUSES",
    "COHORT_POLICY_MODES",
    "DYNAMIC_RESIDENCY_ACTIONS",
    "DYNAMIC_RESIDENCY_RECEIPT_SCHEMA",
    "DYNAMIC_RESIDENCY_RECEIPT_STATUSES",
    "DYNAMIC_RESIDENCY_SCHEMA",
    "EXECUTION_PLAN_SCHEMA",
    "GPU_BACKFILL_SCHEMA",
    "GPU_WAVEFRONT_OBJECTIVES",
    "GPU_WAVEFRONT_SCHEMA",
    "GRANULARITIES",
    "OVERLAP_STATUSES",
    "POLICY_MODES",
    "PROFILE_SCHEMA",
    "QUALITY_RANK",
    "RESIDENCY_PROBLEM_SCHEMA",
    "RUNTIME_PLACEMENT_SCHEMA",
    "LOAD_STATUSES",
    "LAYER_PLACEMENT_SCHEMA",
    "MATMUL_DEVICE_ORDER",
    "MATMUL_PROFILE_SCHEMA",
    "MATMUL_PROFILE_STATUSES",
    "MATMUL_QUEUE_TRANSITIONS",
    "MATMUL_RESULT_SCHEMA",
    "MATMUL_WORKLOAD_SCHEMA",
    "PLACEMENT_PROFILE_SCHEMA",
    "PLACEMENT_STATUSES",
    "OFFLOAD_CONTRACT_SCHEMA",
    "OPERATOR_SPLIT_SCHEMA",
    "PHONE_TRANSPORT_SCHEMA",
    "PHONE_ARBITER_PRIORITIES",
    "PHONE_ARBITER_SCHEMA",
    "PHONE_RESIDENCY_SCHEMA",
    "PHONE_OFFLOAD_EXECUTION_MODES",
    "SESSION_STATES",
    "SMALL_MODEL_OVERLAY_TRACE_SCHEMA",
    "AccountingContract",
    "AccountingKind",
    "AccountingScope",
    "AdaptedTrace",
    "BURSTGPT_TRACE_SCHEMAS",
    "AffineCost",
    "ActivationState",
    "ApplicabilityContract",
    "BackendArtifact",
    "BalancedSplitEstimate",
    "CapacityError",
    "CapacityPlanner",
    "Candidate",
    "CandidatePlan",
    "CandidateSet",
    "CertifiedCohortError",
    "CertifiedCohortProfile",
    "CohortDecision",
    "CohortPolicy",
    "CohortScheduleError",
    "CohortPlanner",
    "CohortRoute",
    "ComputeStep",
    "Decision",
    "DmaBufTransfer",
    "DeviceMemoryCapacity",
    "DYNAMIC_FALLBACK_CONTRACT_SCHEMA",
    "DYNAMIC_FALLBACK_RECEIPT_SCHEMA",
    "DYNAMIC_RESIDENCY_TRANSITION_MODES",
    "DynamicFallbackServiceContract",
    "DynamicFallbackServiceReceipt",
    "DynamicResidencyCandidate",
    "DynamicResidencyDecision",
    "DynamicResidencyError",
    "DynamicResidencyReceipt",
    "DynamicResidencySchedule",
    "DynamicResidencySnapshot",
    "DynamicWeightPlacement",
    "DynamicWeightPlacementSpec",
    "EnergyDomain",
    "EnergyDomainProfile",
    "EnergyProfile",
    "EnergyComponent",
    "ExecutionBranch",
    "ExecutionPlan",
    "ExecutionPlanError",
    "ExecutionStep",
    "FeatureRange",
    "GIB",
    "GpuBackfillCandidate",
    "GpuBackfillDecision",
    "GpuBackfillError",
    "GpuBackfillSchedule",
    "GpuBubbleWindow",
    "GpuReadyChunk",
    "GpuWavefrontDecision",
    "GpuWavefrontSchedule",
    "GpuWavefrontSnapshot",
    "FollowOp",
    "RoutePolicy",
    "HierarchicalPlacementPlanner",
    "KernelEnergyEstimate",
    "KernelEnergyProfile",
    "KERNEL_CAMPAIGN_SCHEMA",
    "KernelCatalog",
    "KernelEstimate",
    "LayerDecision",
    "LayerPlacementCandidate",
    "LayerPlacementContract",
    "LatencyProfile",
    "LatencyVariant",
    "LeaseDemand",
    "LeasePlan",
    "LeasePreview",
    "LeaseRecord",
    "LinkCatalog",
    "LifecycleProfileSet",
    "LifecycleReceipt",
    "MatmulDeviceProfile",
    "MatmulKernelProfile",
    "MatmulLinkProfile",
    "MatmulOp",
    "MatmulPolicy",
    "MatmulScheduleError",
    "MatmulSystemProfile",
    "MatmulPlanner",
    "MemoryLedger",
    "MemoryPoolProfile",
    "MemoryPreview",
    "MemoryRequirement",
    "MIXED_TRACE_SCHEMA",
    "MIXED_TRACE_SCHEMAS",
    "MetricEstimate",
    "ModelIdentity",
    "ModelProgram",
    "OperatorCandidate",
    "OperatorDecision",
    "OperatorOffloadContract",
    "OperatorOffloadInvocation",
    "OperatorNode",
    "OperatorSplitError",
    "OperatorSplitInvocation",
    "OperatorSplitPolicy",
    "OperatorWorkSummary",
    "ParallelSplitBalance",
    "ParallelSplitShapeMeasurement",
    "OperatorEnergyCost",
    "OperatorWork",
    "OverlapEstimate",
    "OverlapProfile",
    "OffloadError",
    "ParallelAssignment",
    "Phase",
    "PhaseLease",
    "PhoneBackendConfig",
    "PhoneArbiterDecision",
    "PhoneArbiterError",
    "PhoneArbiterQueue",
    "PhoneArbiterSchedule",
    "PhoneArbiterWindow",
    "PhoneArmGroup",
    "PhoneArmSignal",
    "PhoneOffloadCandidate",
    "PhoneOffloadDecision",
    "PhoneOffloadSchedule",
    "PhoneResidencyError",
    "PhoneResidencyPlan",
    "PhoneResidencySnapshot",
    "PhoneSessionPlan",
    "PhoneSessionReceipt",
    "PhoneTransportContract",
    "PhoneTransportError",
    "PhoneReadyWork",
    "PlacementDevice",
    "PlacementError",
    "PlacementGranularity",
    "PlacementHardwareProfile",
    "PlacementPlan",
    "PolicyConfig",
    "ProfileBundle",
    "ProfileCatalogError",
    "ProfiledEnergyDomain",
    "ProfiledKernel",
    "ProgramOp",
    "PowerInterval",
    "PowerTimeline",
    "QualityClass",
    "QualityContract",
    "Request",
    "RequestSemantics",
    "ResidentPhoneSlice",
    "QueueRequest",
    "ResidentAllocation",
    "ResidencyPhase",
    "ResidencyResource",
    "ResidencyRequirement",
    "ResidencySchedulerError",
    "ResidencySequence",
    "ResidencySwitch",
    "ResidencyTransitionAction",
    "ResourceLeaseProfile",
    "ResourceProfile",
    "ResourceRequirement",
    "ResourceTimeline",
    "RouteAlternative",
    "RouteMaturity",
    "RouteProfile",
    "RouteSchedule",
    "RouteRuntimeContract",
    "RUNTIME_COST_SCHEMA",
    "RuntimeCostError",
    "RuntimeCostEstimateSet",
    "RuntimeCostEstimator",
    "RuntimeExecutorBinding",
    "RuntimeExecutorRegistry",
    "RuntimeMemoryDemand",
    "RuntimeModelArtifact",
    "RuntimeRouteCostEstimate",
    "RuntimeGateError",
    "RuntimeGateReceipt",
    "RuntimePlacementCandidate",
    "RuntimePlacementDecision",
    "RuntimePlacementError",
    "RuntimePlacementPlanner",
    "RuntimePlacementSnapshot",
    "RuntimeResourceRequirement",
    "RuntimeResourceState",
    "RuntimeSnapshot",
    "SchedulingUnit",
    "ScheduledRequest",
    "SchedulerError",
    "SchedulerContractError",
    "SemanticCapabilities",
    "SEMANTIC_SOURCE_TRACE_SCHEMA",
    "ShapeBucket",
    "SOURCE_TRACE_SCHEMA",
    "TaskPlacementDecision",
    "TaskRoute",
    "TransferDecision",
    "TransferEstimate",
    "TransferLink",
    "TransferStep",
    "TraceError",
    "UnitKind",
    "UnifiedScheduleError",
    "UnifiedScheduler",
    "adapt_legacy_profile",
    "adapt_legacy_request",
    "adapt_legacy_route",
    "apply_dynamic_residency_receipt",
    "build_execution_plan",
    "build_arm_group",
    "build_arm_signal",
    "balance_parallel_split",
    "canonical_profile_bytes",
    "canonical_json",
    "canonical_sha256",
    "cohort_decision_to_json",
    "decision_to_json",
    "estimate_kernel_energy",
    "evaluate_runtime_gate",
    "load_matmul_profile",
    "load_matmul_workload",
    "load_burstgpt_trace",
    "load_lifecycle_profile_set",
    "load_mixed_model_trace",
    "load_profile_bundle",
    "load_trace",
    "load_execution_plan",
    "load_certified_cohort",
    "make_work_set_hash",
    "materialize_matmul_profile",
    "optimize_parallel_assignment",
    "parallel_assignment_to_json",
    "parse_split_table",
    "select_split_columns",
    "placement_plan_to_json",
    "plan_residency_sequence",
    "residency_sequence_to_json",
    "run_matmul_workload",
    "schedule_route",
    "select_energy_positive_offload",
    "select_phone_arbiter_work",
    "select_dynamic_residency_transition",
    "select_gpu_backfill",
    "select_gpu_wavefront_backfill",
    "scheduled_request_to_json",
    "solve_residency_problem",
    "split_table_text",
    "sha256_file",
    "task_placement_to_json",
    "validate_session_transition",
    "write_execution_plan",
]
