"""Unified heterogeneous inference scheduler."""

from ._internal.compat import adapt_legacy_profile, adapt_legacy_request, adapt_legacy_route
from ._internal.capacity import (
    LAYER_PLACEMENT_SCHEMA,
    CapacityError,
    CapacityPlanner,
    DeviceMemoryCapacity,
    LayerPlacementCandidate,
    LayerPlacementContract,
)
from ._internal.adaptive_decode_contracts import (
    ADAPTIVE_DECODE_SCHEMA,
    ADAPTIVE_DECODE_STATES,
    AdaptiveDecodeConfig,
    AdaptiveDecodeControl,
    AdaptiveDecodeDirective,
    AdaptiveDecodeError,
    AdaptiveDecodeGroupedObservation,
    AdaptiveDecodePolicy,
    AdaptiveDecodePolicyAck,
    AdaptiveDecodeRawWindowObservation,
    AdaptiveDecodeWindowBoundary,
    AdaptiveDecodeWindowReceipt,
)
from ._internal.dynamic_residency import (
    DYNAMIC_FALLBACK_CONTRACT_SCHEMA,
    DYNAMIC_FALLBACK_RECEIPT_SCHEMA,
    DYNAMIC_RESIDENCY_ACTIONS,
    DYNAMIC_RESIDENCY_RECEIPT_SCHEMA,
    DYNAMIC_RESIDENCY_RECEIPT_STATUSES,
    DYNAMIC_RESIDENCY_SCHEMA,
    DYNAMIC_RESIDENCY_TRANSITION_MODES,
    DynamicFallbackServiceContract,
    DynamicFallbackServiceReceipt,
    DynamicResidencyCandidate,
    DynamicResidencyDecision,
    DynamicResidencyError,
    DynamicResidencyReceipt,
    DynamicResidencySnapshot,
    DynamicWeightPlacement,
    DynamicWeightPlacementSpec,
    ResidencyTransitionAction,
    apply_dynamic_residency_receipt,
    select_dynamic_residency_transition,
)
from ._internal.gpu_backfill import (
    GPU_BACKFILL_SCHEMA,
    GPU_WAVEFRONT_OBJECTIVES,
    GPU_WAVEFRONT_SCHEMA,
    GpuBackfillCandidate,
    GpuBackfillDecision,
    GpuBackfillError,
    GpuBubbleWindow,
    GpuReadyChunk,
    GpuWavefrontDecision,
    GpuWavefrontSnapshot,
    select_gpu_backfill,
    select_gpu_wavefront_backfill,
)
from ._internal.phone_shards import PhoneFfnShardStorageMetadata
from ._internal.cohort import (
    COHORT_POLICY_MODES,
    CohortDecision,
    CohortPolicy,
    CohortScheduleError,
    CohortPlanner,
    cohort_decision_to_json,
)
from ._internal.certified_cohort import (
    CertifiedCohortError,
    CertifiedCohortProfile,
    load_certified_cohort,
)
from .scheduler import (
    DynamicPlacementLease,
    DynamicResidencySchedule,
    GpuBackfillSchedule,
    GpuWavefrontSchedule,
    LifecycleProfileSet,
    LifecycleReceipt,
    PhoneArbiterSchedule,
    PhoneOffloadSchedule,
    RequestShapeUnsupportedError,
    UnifiedScheduleError,
    UnifiedScheduler,
)
from ._internal.executor import (
    EXECUTION_PLAN_SCHEMA,
    ExecutionPlan,
    ExecutionPlanError,
    build_execution_plan,
    load_execution_plan,
    write_execution_plan,
)
from ._internal.policy import (
    ENERGY_STATUSES,
    GRANULARITIES,
    OVERLAP_STATUSES,
    POLICY_MODES,
    PROFILE_SCHEMA,
    QUALITY_RANK,
    AffineCost,
    Candidate,
    Decision,
    EnergyDomain,
    EnergyProfile,
    RoutePolicy,
    KernelEnergyEstimate,
    KernelEnergyProfile,
    LatencyProfile,
    LatencyVariant,
    LeaseDemand,
    LeasePlan,
    LeasePreview,
    LeaseRecord,
    MarginalSystemCostContext,
    OperatorEnergyCost,
    OperatorWork,
    OverlapProfile,
    PolicyConfig,
    ProfileBundle,
    Request,
    ResourceLeaseProfile,
    ResourceProfile,
    ResourceTimeline,
    RouteProfile,
    SchedulerError,
    decision_to_json,
    estimate_kernel_energy,
)
from ._internal.placement import (
    LOAD_STATUSES,
    PLACEMENT_PROFILE_SCHEMA,
    PLACEMENT_STATUSES,
    ComputeStep,
    ExecutionBranch,
    ExecutionStep,
    HierarchicalPlacementPlanner,
    LayerDecision,
    MemoryPoolProfile,
    OperatorCandidate,
    OperatorDecision,
    OperatorNode,
    PlacementDevice,
    PlacementError,
    PlacementHardwareProfile,
    PlacementPlan,
    ProfiledEnergyDomain,
    ProfiledKernel,
    ResidentAllocation,
    TaskPlacementDecision,
    TaskRoute,
    TransferDecision,
    TransferLink,
    TransferStep,
    placement_plan_to_json,
    task_placement_to_json,
)
from ._internal.offload import (
    OFFLOAD_CONTRACT_SCHEMA,
    BackendArtifact,
    OffloadError,
    OperatorOffloadContract,
    OperatorOffloadInvocation,
    PhoneBackendConfig,
)
from ._internal.operator_split import (
    OPERATOR_SPLIT_SCHEMA,
    BalancedSplitEstimate,
    OperatorSplitError,
    OperatorSplitInvocation,
    OperatorSplitPolicy,
    OperatorWorkSummary,
    ParallelSplitBalance,
    ParallelSplitShapeMeasurement,
    ShapeBucket,
    balance_parallel_split,
    parse_split_table,
    select_split_columns,
    split_table_text,
)
from ._internal.phone_transport import (
    PHONE_TRANSPORT_SCHEMA,
    DmaBufTransfer,
    PhoneTransportContract,
    PhoneTransportError,
)
from ._internal.phone_arbiter import (
    PHONE_ARBITER_PRIORITIES,
    PHONE_ARBITER_SCHEMA,
    PhoneArbiterDecision,
    PhoneArbiterError,
    PhoneArbiterQueue,
    PhoneArbiterWindow,
    PhoneReadyWork,
    select_phone_arbiter_work,
)
from ._internal.phone_residency import (
    PHONE_OFFLOAD_EXECUTION_MODES,
    PHONE_RESIDENCY_SCHEMA,
    SESSION_STATES,
    PhoneArmGroup,
    PhoneArmSignal,
    PhoneOffloadCandidate,
    PhoneOffloadDecision,
    PhoneResidencyError,
    PhoneResidencyPlan,
    PhoneResidencySnapshot,
    PhoneSessionPlan,
    PhoneSessionReceipt,
    ResidentPhoneSlice,
    build_arm_group,
    build_arm_signal,
    select_energy_positive_offload,
    validate_session_transition,
)
from ._internal.offline_phone_residency import (
    OfflinePhoneResidencyPlan,
    OfflinePhoneResidencyStage,
)
from ._internal.desktop_parent import (
    DesktopParentCapacityCandidate,
    DesktopParentCapacityError,
    DesktopParentCapacitySelection,
    select_desktop_parent_for_live_vram,
)
from ._internal.profile_catalog import (
    ProfileCatalogError,
    canonical_profile_bytes,
    load_lifecycle_profile_set,
    load_profile_bundle,
)
from ._internal.profile_materializer import (
    GIB,
    KERNEL_CAMPAIGN_SCHEMA,
    materialize_matmul_profile,
)
from ._internal.residency import (
    RESIDENCY_PROBLEM_SCHEMA,
    CohortRoute,
    ParallelAssignment,
    QueueRequest,
    ResidencyPhase,
    ResidencyResource,
    ResidencySchedulerError,
    ResidencySequence,
    ResidencySwitch,
    RouteSchedule,
    ScheduledRequest,
    optimize_parallel_assignment,
    parallel_assignment_to_json,
    plan_residency_sequence,
    residency_sequence_to_json,
    schedule_route,
    scheduled_request_to_json,
    solve_residency_problem,
)
from ._internal.runtime_gates import (
    RequestSemantics,
    ResourceRequirement as RuntimeResourceRequirement,
    RouteRuntimeContract,
    RuntimeGateError,
    RuntimeGateReceipt,
    RuntimeResourceState,
    RuntimeSnapshot,
    SemanticCapabilities,
    evaluate_runtime_gate,
)
from ._internal.runtime_placement import (
    RUNTIME_PLACEMENT_SCHEMA,
    RuntimePlacementCandidate,
    RuntimePlacementDecision,
    RuntimePlacementError,
    RuntimePlacementPlanner,
    RuntimePlacementSnapshot,
)
from ._internal.runtime_cost import (
    RUNTIME_COST_SCHEMA,
    RuntimeCostError,
    RuntimeCostEstimateSet,
    RuntimeCostEstimator,
    RuntimeExecutorBinding,
    RuntimeExecutorRegistry,
    RuntimeParticipantBinding,
    RuntimeMemoryDemand,
    RuntimeModelArtifact,
    RuntimeRouteCostEstimate,
)
from ._internal.model_manifest import (
    GGUFModelManifestLoader,
    MODEL_MANIFEST_SCHEMA,
    ModelManifest,
    ModelManifestError,
    ModelOperatorManifest,
    ModelRequestWork,
    ModelTensorManifest,
    OperatorWorkEstimate,
)
from ._internal.model_manifest_cache import load_cached_gguf_manifest
from ._internal.runtime_capabilities import (
    HeterogeneousRuntimeSnapshot,
    ModelResidencyObservation,
    ROUTE_MATURITY_STATES,
    RuntimeCapabilityCatalog,
    RuntimeCapabilityError,
    RuntimeCompositeExecutorCapability,
    RuntimeCompositeOperatorPlacement,
    RuntimeDesktopControlProfile,
    RuntimeExecutorCapability,
    RuntimeExecutorState,
    RuntimeKernelShapeProfile,
    RuntimeLinkState,
    RuntimePhoneSessionCapability,
    RuntimePhonePowerProfile,
    RuntimeRouteShapeProfile,
    RuntimeTransitionCapability,
)
from ._internal.runtime_system_cost import (
    RuntimeProtectedWorkObservation,
    RuntimeSystemCostError,
    RuntimeSystemCostProfile,
)
from ._internal.runtime_plan import (
    AutomatedCandidateSet,
    AutomatedRouteCandidate,
    AutomatedRouteCost,
    RuntimeExecutionContract,
    RuntimeExecutionPlan,
    RuntimeExecutionReceipt,
    RuntimeOperatorAssignment,
    RuntimePhoneShard,
    RuntimeResidencyEviction,
    RuntimeTransitionReceipt,
    RuntimeTransitionPlan,
)
from ._internal.runtime_resources import (
    RuntimeMemoryReservation,
    RuntimeResourceError,
)
from ._internal.online_placement import (
    ONLINE_PLACEMENT_SCHEMA,
    ONLINE_ROUTE_FAMILIES,
    OnlinePlacementError,
    OnlinePlacementReceipt,
    OnlinePlacementTracker,
    OnlineRouteFamilyEstimate,
)
from ._internal.runtime_dispatch_policy import (
    RuntimeDispatchPolicy,
    RuntimeDispatchPolicyError,
)
from ._internal.runtime_queue import (
    RUNTIME_DISPATCH_QUEUE_SCHEMA,
    BackgroundRuntimeMonitor,
    BackgroundRuntimeSnapshot,
    RuntimeDispatchQueue,
    RuntimeDispatchReceipt,
    RuntimeQueueError,
)
from ._internal.runtime_controller import (
    RUNTIME_REQUEST_TICKET_SCHEMA,
    RuntimeCompletionReceipt,
    RuntimeControllerError,
    RuntimeFailureRecovery,
    RuntimeLatencyUpperBound,
    RuntimeLeaseCoverage,
    RuntimeLeaseExtensionReceipt,
    RuntimeRequestTicket,
    assess_runtime_completion,
)
from ._internal.runtime_admission import (
    RuntimeAdmissionError,
    RuntimeExecutorObservation,
    RuntimeRequestObservation,
)
from ._internal.runtime_execution import (
    RuntimeExecutionCoordinatorError,
    RuntimeExecutionFailure,
)
from ._internal.runtime_phase import (
    RuntimePhaseError,
    RuntimePhaseObservation,
)
from ._internal.decision_log import (
    DECISION_LOG_SCHEMA,
    DecisionLogError,
)
from ._internal.types import (
    AccountingContract,
    AccountingKind,
    AccountingScope,
    ApplicabilityContract,
    CandidateSet,
    EnergyComponent,
    FeatureRange,
    MemoryRequirement,
    MetricEstimate,
    ModelIdentity,
    OverlapEstimate,
    PhaseLease,
    PlacementGranularity,
    QualityClass,
    QualityContract,
    ResidencyRequirement,
    ResourceRequirement,
    RouteAlternative,
    RouteMaturity,
    SchedulingUnit,
    SchedulerContractError,
    UnitKind,
    canonical_json,
    canonical_sha256,
    make_work_set_hash,
)
from .trace import (
    AdaptedTrace,
    BURSTGPT_TRACE_SCHEMAS,
    MIXED_TRACE_SCHEMA,
    MIXED_TRACE_SCHEMAS,
    SEMANTIC_SOURCE_TRACE_SCHEMA,
    SMALL_MODEL_OVERLAY_TRACE_SCHEMA,
    SOURCE_TRACE_SCHEMA,
    TraceError,
    load_burstgpt_trace,
    load_mixed_model_trace,
    load_trace,
    sha256_file,
)
from .config import (
    CAMPAIGN_MANIFEST_SCHEMA,
    EVIDENCE_MANIFEST_SCHEMA,
    MODELS_MANIFEST_SCHEMA,
    RESOLVED_CONFIGURATION_SCHEMA,
    RIG_MANIFEST_SCHEMA,
    CampaignManifest,
    CampaignModelConfiguration,
    ConfigurationOverride,
    EvidenceManifest,
    ManifestIdentity,
    ModelsManifest,
    PhonePowerEvidenceConfiguration,
    PhoneRigConfiguration,
    ResolvedSchedulerConfiguration,
    RigDeviceConfiguration,
    RigManifest,
    RigResourceConfiguration,
    RigTopologyConfiguration,
    SchedulerConfigurationError,
    TraceConfiguration,
    load_scheduler_configuration,
    write_resolved_configuration,
)
from .configuration.campaign import ELASTIC_PHONES_DEFAULTS, elastic_phones_configuration
from ._unified.adaptive_decode_control import (
    DEVICE_ABSENT_AT_START,
    DEVICE_MEMBERSHIP_EVENT_KINDS,
    device_quarantine_resource_ids,
)


_MATMUL_EXPORTS = {
    "MATMUL_DEVICE_ORDER": "DEVICE_ORDER",
    "MATMUL_PROFILE_SCHEMA": "PROFILE_SCHEMA",
    "MATMUL_PROFILE_STATUSES": "PROFILE_STATUSES",
    "MATMUL_QUEUE_TRANSITIONS": "QUEUE_TRANSITIONS",
    "MATMUL_RESULT_SCHEMA": "RESULT_SCHEMA",
    "MATMUL_WORKLOAD_SCHEMA": "WORKLOAD_SCHEMA",
    "ActivationState": "ActivationState",
    "CandidatePlan": "CandidatePlan",
    "EnergyDomainProfile": "EnergyDomainProfile",
    "FollowOp": "FollowOp",
    "KernelCatalog": "KernelCatalog",
    "KernelEstimate": "KernelEstimate",
    "LinkCatalog": "LinkCatalog",
    "MatmulDeviceProfile": "MatmulDeviceProfile",
    "MatmulKernelProfile": "MatmulKernelProfile",
    "MatmulLinkProfile": "MatmulLinkProfile",
    "MatmulOp": "MatmulOp",
    "MatmulPolicy": "MatmulPolicy",
    "MatmulScheduleError": "MatmulScheduleError",
    "MatmulSystemProfile": "MatmulSystemProfile",
    "MatmulPlanner": "MatmulPlanner",
    "MemoryLedger": "MemoryLedger",
    "MemoryPreview": "MemoryPreview",
    "ModelProgram": "ModelProgram",
    "Phase": "Phase",
    "PowerInterval": "PowerInterval",
    "PowerTimeline": "PowerTimeline",
    "ProgramOp": "ProgramOp",
    "TransferEstimate": "TransferEstimate",
    "load_matmul_profile": "load_profile",
    "load_matmul_workload": "load_workload",
    "run_matmul_workload": "run_workload",
}


def __getattr__(name: str) -> object:
    try:
        target = _MATMUL_EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(name) from exc
    from importlib import import_module

    module = import_module("._internal.matmul", __name__)
    value = getattr(module, target)
    globals()[name] = value
    return value

__all__ = [
    'ADAPTIVE_DECODE_SCHEMA',
    'ADAPTIVE_DECODE_STATES',
    'AccountingContract',
    'AccountingKind',
    'AccountingScope',
    'ActivationState',
    'AdaptedTrace',
    'AdaptiveDecodeConfig',
    'AdaptiveDecodeControl',
    'AdaptiveDecodeDirective',
    'AdaptiveDecodeError',
    'AdaptiveDecodeGroupedObservation',
    'AdaptiveDecodePolicy',
    'AdaptiveDecodePolicyAck',
    'AdaptiveDecodeRawWindowObservation',
    'AdaptiveDecodeWindowBoundary',
    'AdaptiveDecodeWindowReceipt',
    'AffineCost',
    'ApplicabilityContract',
    'AutomatedCandidateSet',
    'AutomatedRouteCandidate',
    'AutomatedRouteCost',
    'BURSTGPT_TRACE_SCHEMAS',
    'BackendArtifact',
    'BackgroundRuntimeMonitor',
    'BackgroundRuntimeSnapshot',
    'BalancedSplitEstimate',
    'CAMPAIGN_MANIFEST_SCHEMA',
    'COHORT_POLICY_MODES',
    'CampaignManifest',
    'CampaignModelConfiguration',
    'Candidate',
    'CandidatePlan',
    'CandidateSet',
    'CapacityError',
    'CapacityPlanner',
    'CertifiedCohortError',
    'CertifiedCohortProfile',
    'CohortDecision',
    'CohortPlanner',
    'CohortPolicy',
    'CohortRoute',
    'CohortScheduleError',
    'ComputeStep',
    'ConfigurationOverride',
    'DECISION_LOG_SCHEMA',
    'DEVICE_ABSENT_AT_START',
    'DEVICE_MEMBERSHIP_EVENT_KINDS',
    'DYNAMIC_FALLBACK_CONTRACT_SCHEMA',
    'DYNAMIC_FALLBACK_RECEIPT_SCHEMA',
    'DYNAMIC_RESIDENCY_ACTIONS',
    'DYNAMIC_RESIDENCY_RECEIPT_SCHEMA',
    'DYNAMIC_RESIDENCY_RECEIPT_STATUSES',
    'DYNAMIC_RESIDENCY_SCHEMA',
    'DYNAMIC_RESIDENCY_TRANSITION_MODES',
    'Decision',
    'DecisionLogError',
    'DesktopParentCapacityCandidate',
    'DesktopParentCapacityError',
    'DesktopParentCapacitySelection',
    'DeviceMemoryCapacity',
    'DmaBufTransfer',
    'DynamicFallbackServiceContract',
    'DynamicFallbackServiceReceipt',
    'DynamicPlacementLease',
    'DynamicResidencyCandidate',
    'DynamicResidencyDecision',
    'DynamicResidencyError',
    'DynamicResidencyReceipt',
    'DynamicResidencySchedule',
    'DynamicResidencySnapshot',
    'DynamicWeightPlacement',
    'DynamicWeightPlacementSpec',
    'ELASTIC_PHONES_DEFAULTS',
    'ENERGY_STATUSES',
    'EVIDENCE_MANIFEST_SCHEMA',
    'EXECUTION_PLAN_SCHEMA',
    'EnergyComponent',
    'EnergyDomain',
    'EnergyDomainProfile',
    'EnergyProfile',
    'EvidenceManifest',
    'ExecutionBranch',
    'ExecutionPlan',
    'ExecutionPlanError',
    'ExecutionStep',
    'FeatureRange',
    'FollowOp',
    'GGUFModelManifestLoader',
    'GIB',
    'GPU_BACKFILL_SCHEMA',
    'GPU_WAVEFRONT_OBJECTIVES',
    'GPU_WAVEFRONT_SCHEMA',
    'GRANULARITIES',
    'GpuBackfillCandidate',
    'GpuBackfillDecision',
    'GpuBackfillError',
    'GpuBackfillSchedule',
    'GpuBubbleWindow',
    'GpuReadyChunk',
    'GpuWavefrontDecision',
    'GpuWavefrontSchedule',
    'GpuWavefrontSnapshot',
    'HeterogeneousRuntimeSnapshot',
    'HierarchicalPlacementPlanner',
    'KERNEL_CAMPAIGN_SCHEMA',
    'KernelCatalog',
    'KernelEnergyEstimate',
    'KernelEnergyProfile',
    'KernelEstimate',
    'LAYER_PLACEMENT_SCHEMA',
    'LOAD_STATUSES',
    'LatencyProfile',
    'LatencyVariant',
    'LayerDecision',
    'LayerPlacementCandidate',
    'LayerPlacementContract',
    'LeaseDemand',
    'LeasePlan',
    'LeasePreview',
    'LeaseRecord',
    'LifecycleProfileSet',
    'LifecycleReceipt',
    'LinkCatalog',
    'MATMUL_DEVICE_ORDER',
    'MATMUL_PROFILE_SCHEMA',
    'MATMUL_PROFILE_STATUSES',
    'MATMUL_QUEUE_TRANSITIONS',
    'MATMUL_RESULT_SCHEMA',
    'MATMUL_WORKLOAD_SCHEMA',
    'MIXED_TRACE_SCHEMA',
    'MIXED_TRACE_SCHEMAS',
    'MODELS_MANIFEST_SCHEMA',
    'MODEL_MANIFEST_SCHEMA',
    'ManifestIdentity',
    'MarginalSystemCostContext',
    'MatmulDeviceProfile',
    'MatmulKernelProfile',
    'MatmulLinkProfile',
    'MatmulOp',
    'MatmulPlanner',
    'MatmulPolicy',
    'MatmulScheduleError',
    'MatmulSystemProfile',
    'MemoryLedger',
    'MemoryPoolProfile',
    'MemoryPreview',
    'MemoryRequirement',
    'MetricEstimate',
    'ModelIdentity',
    'ModelManifest',
    'ModelManifestError',
    'ModelOperatorManifest',
    'ModelProgram',
    'ModelRequestWork',
    'ModelResidencyObservation',
    'ModelTensorManifest',
    'ModelsManifest',
    'OFFLOAD_CONTRACT_SCHEMA',
    'ONLINE_PLACEMENT_SCHEMA',
    'ONLINE_ROUTE_FAMILIES',
    'OPERATOR_SPLIT_SCHEMA',
    'OVERLAP_STATUSES',
    'OfflinePhoneResidencyPlan',
    'OfflinePhoneResidencyStage',
    'OffloadError',
    'OnlinePlacementError',
    'OnlinePlacementReceipt',
    'OnlinePlacementTracker',
    'OnlineRouteFamilyEstimate',
    'OperatorCandidate',
    'OperatorDecision',
    'OperatorEnergyCost',
    'OperatorNode',
    'OperatorOffloadContract',
    'OperatorOffloadInvocation',
    'OperatorSplitError',
    'OperatorSplitInvocation',
    'OperatorSplitPolicy',
    'OperatorWork',
    'OperatorWorkEstimate',
    'OperatorWorkSummary',
    'OverlapEstimate',
    'OverlapProfile',
    'PHONE_ARBITER_PRIORITIES',
    'PHONE_ARBITER_SCHEMA',
    'PHONE_OFFLOAD_EXECUTION_MODES',
    'PHONE_RESIDENCY_SCHEMA',
    'PHONE_TRANSPORT_SCHEMA',
    'PLACEMENT_PROFILE_SCHEMA',
    'PLACEMENT_STATUSES',
    'POLICY_MODES',
    'PROFILE_SCHEMA',
    'ParallelAssignment',
    'ParallelSplitBalance',
    'ParallelSplitShapeMeasurement',
    'Phase',
    'PhaseLease',
    'PhoneArbiterDecision',
    'PhoneArbiterError',
    'PhoneArbiterQueue',
    'PhoneArbiterSchedule',
    'PhoneArbiterWindow',
    'PhoneArmGroup',
    'PhoneArmSignal',
    'PhoneBackendConfig',
    'PhoneFfnShardStorageMetadata',
    'PhoneOffloadCandidate',
    'PhoneOffloadDecision',
    'PhoneOffloadSchedule',
    'PhonePowerEvidenceConfiguration',
    'PhoneReadyWork',
    'PhoneResidencyError',
    'PhoneResidencyPlan',
    'PhoneResidencySnapshot',
    'PhoneRigConfiguration',
    'PhoneSessionPlan',
    'PhoneSessionReceipt',
    'PhoneTransportContract',
    'PhoneTransportError',
    'PlacementDevice',
    'PlacementError',
    'PlacementGranularity',
    'PlacementHardwareProfile',
    'PlacementPlan',
    'PolicyConfig',
    'PowerInterval',
    'PowerTimeline',
    'ProfileBundle',
    'ProfileCatalogError',
    'ProfiledEnergyDomain',
    'ProfiledKernel',
    'ProgramOp',
    'QUALITY_RANK',
    'QualityClass',
    'QualityContract',
    'QueueRequest',
    'RESIDENCY_PROBLEM_SCHEMA',
    'RESOLVED_CONFIGURATION_SCHEMA',
    'RIG_MANIFEST_SCHEMA',
    'ROUTE_MATURITY_STATES',
    'RUNTIME_COST_SCHEMA',
    'RUNTIME_DISPATCH_QUEUE_SCHEMA',
    'RUNTIME_PLACEMENT_SCHEMA',
    'RUNTIME_REQUEST_TICKET_SCHEMA',
    'Request',
    'RequestSemantics',
    'RequestShapeUnsupportedError',
    'ResidencyPhase',
    'ResidencyRequirement',
    'ResidencyResource',
    'ResidencySchedulerError',
    'ResidencySequence',
    'ResidencySwitch',
    'ResidencyTransitionAction',
    'ResidentAllocation',
    'ResidentPhoneSlice',
    'ResolvedSchedulerConfiguration',
    'ResourceLeaseProfile',
    'ResourceProfile',
    'ResourceRequirement',
    'ResourceTimeline',
    'RigDeviceConfiguration',
    'RigManifest',
    'RigResourceConfiguration',
    'RigTopologyConfiguration',
    'RouteAlternative',
    'RouteMaturity',
    'RoutePolicy',
    'RouteProfile',
    'RouteRuntimeContract',
    'RouteSchedule',
    'RuntimeAdmissionError',
    'RuntimeCapabilityCatalog',
    'RuntimeCapabilityError',
    'RuntimeCompletionReceipt',
    'RuntimeCompositeExecutorCapability',
    'RuntimeCompositeOperatorPlacement',
    'RuntimeControllerError',
    'RuntimeCostError',
    'RuntimeCostEstimateSet',
    'RuntimeCostEstimator',
    'RuntimeDesktopControlProfile',
    'RuntimeDispatchPolicy',
    'RuntimeDispatchPolicyError',
    'RuntimeDispatchQueue',
    'RuntimeDispatchReceipt',
    'RuntimeExecutionContract',
    'RuntimeExecutionCoordinatorError',
    'RuntimeExecutionFailure',
    'RuntimeExecutionPlan',
    'RuntimeExecutionReceipt',
    'RuntimeExecutorBinding',
    'RuntimeExecutorCapability',
    'RuntimeExecutorObservation',
    'RuntimeExecutorRegistry',
    'RuntimeExecutorState',
    'RuntimeFailureRecovery',
    'RuntimeGateError',
    'RuntimeGateReceipt',
    'RuntimeKernelShapeProfile',
    'RuntimeLatencyUpperBound',
    'RuntimeLeaseCoverage',
    'RuntimeLeaseExtensionReceipt',
    'RuntimeLinkState',
    'RuntimeMemoryDemand',
    'RuntimeMemoryReservation',
    'RuntimeModelArtifact',
    'RuntimeOperatorAssignment',
    'RuntimeParticipantBinding',
    'RuntimePhaseError',
    'RuntimePhaseObservation',
    'RuntimePhonePowerProfile',
    'RuntimePhoneSessionCapability',
    'RuntimePhoneShard',
    'RuntimePlacementCandidate',
    'RuntimePlacementDecision',
    'RuntimePlacementError',
    'RuntimePlacementPlanner',
    'RuntimePlacementSnapshot',
    'RuntimeProtectedWorkObservation',
    'RuntimeQueueError',
    'RuntimeRequestObservation',
    'RuntimeRequestTicket',
    'RuntimeResidencyEviction',
    'RuntimeResourceError',
    'RuntimeResourceRequirement',
    'RuntimeResourceState',
    'RuntimeRouteCostEstimate',
    'RuntimeRouteShapeProfile',
    'RuntimeSnapshot',
    'RuntimeSystemCostError',
    'RuntimeSystemCostProfile',
    'RuntimeTransitionCapability',
    'RuntimeTransitionPlan',
    'RuntimeTransitionReceipt',
    'SEMANTIC_SOURCE_TRACE_SCHEMA',
    'SESSION_STATES',
    'SMALL_MODEL_OVERLAY_TRACE_SCHEMA',
    'SOURCE_TRACE_SCHEMA',
    'ScheduledRequest',
    'SchedulerConfigurationError',
    'SchedulerContractError',
    'SchedulerError',
    'SchedulingUnit',
    'SemanticCapabilities',
    'ShapeBucket',
    'TaskPlacementDecision',
    'TaskRoute',
    'TraceConfiguration',
    'TraceError',
    'TransferDecision',
    'TransferEstimate',
    'TransferLink',
    'TransferStep',
    'UnifiedScheduleError',
    'UnifiedScheduler',
    'UnitKind',
    'adapt_legacy_profile',
    'adapt_legacy_request',
    'adapt_legacy_route',
    'apply_dynamic_residency_receipt',
    'assess_runtime_completion',
    'balance_parallel_split',
    'build_arm_group',
    'build_arm_signal',
    'build_execution_plan',
    'canonical_json',
    'canonical_profile_bytes',
    'canonical_sha256',
    'cohort_decision_to_json',
    'decision_to_json',
    'device_quarantine_resource_ids',
    'elastic_phones_configuration',
    'estimate_kernel_energy',
    'evaluate_runtime_gate',
    'load_burstgpt_trace',
    'load_cached_gguf_manifest',
    'load_certified_cohort',
    'load_execution_plan',
    'load_lifecycle_profile_set',
    'load_matmul_profile',
    'load_matmul_workload',
    'load_mixed_model_trace',
    'load_profile_bundle',
    'load_scheduler_configuration',
    'load_trace',
    'make_work_set_hash',
    'materialize_matmul_profile',
    'optimize_parallel_assignment',
    'parallel_assignment_to_json',
    'parse_split_table',
    'placement_plan_to_json',
    'plan_residency_sequence',
    'residency_sequence_to_json',
    'run_matmul_workload',
    'schedule_route',
    'scheduled_request_to_json',
    'select_desktop_parent_for_live_vram',
    'select_dynamic_residency_transition',
    'select_energy_positive_offload',
    'select_gpu_backfill',
    'select_gpu_wavefront_backfill',
    'select_phone_arbiter_work',
    'select_split_columns',
    'sha256_file',
    'solve_residency_problem',
    'split_table_text',
    'task_placement_to_json',
    'validate_session_transition',
    'write_execution_plan',
    'write_resolved_configuration',
]
